<?php
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');
$pdo=new PDO('mysql:host=localhost;dbname=testorder;charset=utf8mb4','root','',[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$pdo->exec("CREATE TABLE IF NOT EXISTS services (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(255) NOT NULL,description TEXT NULL,price VARCHAR(255) NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$pdo->exec("CREATE TABLE IF NOT EXISTS reviews (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(255) NOT NULL,text TEXT NOT NULL,rating TINYINT UNSIGNED NOT NULL DEFAULT 5,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$pdo->exec("CREATE TABLE IF NOT EXISTS portfolio (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) NOT NULL,description TEXT NULL,image VARCHAR(500) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
try{$method=$_SERVER['REQUEST_METHOD'];$type=$_GET['type']??'services';$tables=['services'=>'services','reviews'=>'reviews','portfolio'=>'portfolio'];if(!isset($tables[$type]))throw new RuntimeException('Неизвестный раздел');$table=$tables[$type];
if($method==='GET'){echo json_encode($pdo->query("SELECT * FROM $table ORDER BY id DESC")->fetchAll(),JSON_UNESCAPED_UNICODE);exit;}
if($method==='DELETE'){ $id=(int)($_GET['id']??0);if(!$id)throw new RuntimeException('Не указан ID');if($table==='portfolio'){$s=$pdo->prepare("SELECT image FROM portfolio WHERE id=?");$s->execute([$id]);$x=$s->fetch();if($x&&is_file(__DIR__.'/'.$x['image']))@unlink(__DIR__.'/'.$x['image']);}$pdo->prepare("DELETE FROM $table WHERE id=?")->execute([$id]);echo json_encode(['status'=>'success']);exit;}
$data=$_POST;$id=(int)($data['id']??0);$upload=null;if($type==='portfolio'&&!empty($_FILES['image']['tmp_name'])){$f=$_FILES['image'];if($f['error']!==UPLOAD_ERR_OK||$f['size']>5*1024*1024)throw new RuntimeException('Фото должно быть до 5 МБ');$info=@getimagesize($f['tmp_name']);$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];if(!$info||!isset($allowed[$info['mime']]))throw new RuntimeException('Разрешены JPG, PNG и WebP');$dir=__DIR__.'/uploads/portfolio';if(!is_dir($dir))mkdir($dir,0755,true);$name=bin2hex(random_bytes(16)).'.'.$allowed[$info['mime']];move_uploaded_file($f['tmp_name'],$dir.'/'.$name);$upload='uploads/portfolio/'.$name;}
if($type==='services'){$name=trim($data['name']??'');$desc=trim($data['description']??'');$price=trim($data['price']??'');if(!$name)throw new RuntimeException('Название услуги обязательно');if($id){$s=$pdo->prepare('UPDATE services SET name=?,description=?,price=? WHERE id=?');$s->execute([$name,$desc,$price,$id]);}else{$s=$pdo->prepare('INSERT INTO services(name,description,price) VALUES(?,?,?)');$s->execute([$name,$desc,$price]);}}
elseif($type==='reviews'){$name=trim($data['name']??'');$text=trim($data['text']??'');$rating=max(1,min(5,(int)($data['rating']??5)));if(!$name||!$text)throw new RuntimeException('Имя и текст отзыва обязательны');if($id){$s=$pdo->prepare('UPDATE reviews SET name=?,text=?,rating=? WHERE id=?');$s->execute([$name,$text,$rating,$id]);}else{$s=$pdo->prepare('INSERT INTO reviews(name,text,rating) VALUES(?,?,?)');$s->execute([$name,$text,$rating]);}}
else{$title=trim($data['title']??'');$desc=trim($data['description']??'');if(!$title)throw new RuntimeException('Название работы обязательно');if(!$id&&!$upload)throw new RuntimeException('Загрузите фото');if($id){if($upload){$s=$pdo->prepare('SELECT image FROM portfolio WHERE id=?');$s->execute([$id]);$old=$s->fetch();$pdo->prepare('UPDATE portfolio SET title=?,description=?,image=? WHERE id=?')->execute([$title,$desc,$upload,$id]);if($old&&is_file(__DIR__.'/'.$old['image']))@unlink(__DIR__.'/'.$old['image']);}else{$pdo->prepare('UPDATE portfolio SET title=?,description=? WHERE id=?')->execute([$title,$desc,$id]);}}else{$pdo->prepare('INSERT INTO portfolio(title,description,image) VALUES(?,?,?)')->execute([$title,$desc,$upload]);}}
echo json_encode(['status'=>'success','id'=>$id?:$pdo->lastInsertId()],JSON_UNESCAPED_UNICODE);
}catch(Throwable $e){http_response_code(400);echo json_encode(['status'=>'error','message'=>$e->getMessage()],JSON_UNESCAPED_UNICODE);}